[package]
name = "rust-snippet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-snippet = "0.6.5"
superslice = "=1.0.0"
itertools = "=0.9.0"
nalgebra = "=0.20.0"

[profile.dev]
opt-level = 3